FROM plugins/base:multiarch

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Manifest" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

COPY drone-manifest /bin/
COPY manifest-tool /bin/
ENTRYPOINT ["/bin/drone-manifest"]
